### ISSUE TITLE
How to analysis the terrorism data

### ISSUE THREAD

**Issue by xueyagaga** [cmjt/stelfi#5]
Dear author
I am very interested in the mentioned Iraq terrrorism data in _stelfi_. 
In specific, I'm curious if terrorist attacks also have the characteristics of the Hawkes Point process.
So, how can we use and analysis this dataset. There seems no related tutorial.
Thanks a lot.

**Comment by cmjt** [comment]
Kia ora,

My advice would be to follow along the Twitter [example here](https://cmjt.github.io/stelfi/hawkes.html#the-fit_hawkes-function). The one issue with the GTD data however is that it's typically only supplied at a daily resolution (essentially binned) and the Hawkes model in stelfi requires unique and "continuous" time stamps. If you have data with this level of temporal resolution then following along the Twitter example should work smoothly. Apologies for the sparse documentation! I am in the process of adding more tutorials etc. to the website :)
